project:
  type: website
  output-dir: docs

website:
  title: "30 Day Map Challenge 2023"
  sidebar:
    contents:
      - index.qmd 
      - auto: maps/
    floating: true
  page-navigation: true

format:
  html:
    theme: 
      - litera
    toc: true
    df-print: kable
