project:
  type: website
  output-dir: docs

website:
  title: "30 Day Map Challenge 2023"
  navbar:
    left:
      - href: index.qmd
        text: The Maps
    pinned: true

format:
  html:
    theme: 
      - slate
      # - custom.scss
    toc: true
    # css: styles.css
    df-print: kable



